version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017' # make sure we don't have another mongo container running on same port
    env_file:
      - .env.local
    volumes:
      - mongo-data:/data/db/
volumes:
  mongo-data:
    driver: local